#ifndef DRONE_EKF_QUATERNIONBASE_PLUGIN
#define DRONE_EKF_QUATERNIONBASE_PLUGIN

#ifndef EIGEN_QUATERNIONBASE_PLUGIN
#define EIGEN_QUATERNIONBASE_PLUGIN <drone_ekf/eigen/QuaternionBaseAddons.h>
#endif

#else  // DRONE_EKF_QUATERNIONBASE_PLUGIN


#endif